### ISSUE TITLE
Remove-HL7Identifiers in Core 7 not working

### ISSUE THREAD

**Issue by Toolazy2work** [RobHolme/HL7-Powershell-Module#2]
Hello

The issue i am having is this commandlette isnt masking the identifiers.  It is creating a new MASKED_filename.hl7 file but all of the information is left intact.  FYI, this is an awesome library youve built and im very happy to be using it!.

**Comment by Toolazy2work** [comment]
After a little more investigation, It seems that it is having a problem going to the next line of the HL7 message.

**Comment by RobHolme** [comment]
I'd really only used it to mask the PID and NK1 segments, by default only the following fields are masked:
 - All PID fields except {"PID-1, PID-2, PID-3"}
 - All NK1 fields except {"NK1-1, NK1-3"}
 - All IN1 fields
-  All IN2 fields

I assume your sample only contains a PID segment from the above list so it appears only one segment is processed. 

There are numerous other segments/fields that can potentially include identifiable information. The CmdLet allows you to list custom segments, fields, and components to mask so you can add your own specific to your messages. e.g.

`
Remove-HL7Identifiers -Path c:\test\testfile.hl7 -CustomItemsList PID-3.1,PID-5,NK1,DG1
`

Note: The CustomItemsList parameter only masks these items, so the default fields I listed above are no longer masked unless you include these in the CustomItemsList.

Give this a go.

**Comment by Toolazy2work** [comment]
my HL7 file has many different segments.  Additionally, i believe the
problem comes from an inability to go to new lines.  Is that expected
behavior or should it be able to navigate to each line of the file?

**Comment by RobHolme** [comment]
I think I've reproduced the issue. Looks like it was expecting windows style line terminations (CRLF), and has an issue with linux line termination (LF). I use Windows predominately so not something I tested. Due to this error only the first segment will be parsed.

I'll fix this - may have to wait until the weekend until I can find some free time. Looks like most other commands in this module will be impacted by non-windows line endings as well. 

Until it is fixed a short term workaround may be to change the line endings from CR to CRLF.

[Update - looks like a one line fix to correct this for all commands, I'll get onto it soon]

**Comment by RobHolme** [comment]
Updated version released - let me know if this fixes the issue.

**Comment by Toolazy2work** [comment]
Rob,
  This is the EXACT Issue I found!  after looking at the files in HEX i saw
"0a" used to end the line instead of "0d".  I think your fix corrected the
problem but still need to test.  Ill let you know.  Thank you so much for
such a quick response and resolution to the issue!

**Comment by Toolazy2work** [comment]
Just Tested and this corrected the Issue!  Youre doing good work here.  Thank you so much for this!
