### ISSUE TITLE
Filter returns more matches than expected

### ISSUE THREAD

**Issue by srikcgaa2** [RobHolme/HL7-Powershell-Module#7]
[202208300638_001738_ORU^R01.txt](https://github.com/RobHolme/HL7-Powershell-Module/files/9453138/202208300638_001738_ORU.R01.txt)

Hi

I have the attached HL7 file and I am trying to get only the OBX-3 Segments where OBX-2=NM.  For this, I am using the following line but it is not restricting to the filter condition

`Select-HL7Item -path <file> -ItemPosition OBX-3 -Filter OBX-2=NM`

It gives me 13 matching lines when I am expecting to get only 3 lines because there are only 3 OBX matching NM as OBX-2. 

Any help on clarifying what I am missing here would be very much appreciated

Thanks in Advance

**Comment by srikcgaa2** [comment]
In the same file, if I do 

`Select-HL7Item -path <file> -ItemPosition OBX-18.1 -Filter OBX-1=1 `

it works properly to get me the value I am interested in

**Comment by RobHolme** [comment]
Hi,

From memory I think I return all repeats of an item if a match was found in any of the repeats. Might be useful for a repeating fields, but doesn't really make sense for repeating segments like in your example. Or possibly just an defect I never tested 😉 . If I find time on the weekend I'll take a look at what would be involved in fixing this.

regards,
Rob.
________________________________
From: srikcgaa2 ***@***.***>
Sent: Tuesday, 30 August 2022 9:30 PM
To: RobHolme/HL7-Powershell-Module ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RobHolme/HL7-Powershell-Module] Query on Filtering in a repeating element (Issue #7)


202208300638_001738_ORU^R01.txt<https://github.com/RobHolme/HL7-Powershell-Module/files/9453138/202208300638_001738_ORU.R01.txt>

Hi

I have the attached HL7 file and I am trying to get only the OBX-3 Segments where OBX-2=NM. For this, I am using the following line but it is not restricting to the filter condition

Select-HL7Item -path -ItemPosition OBX-3 -Filter OBX-2=NM

It gives me 13 when I am expecting to get only 3 because there are only 3 OBX matching NM as OBX-2.

Any help on clarifying what I am missing here would be very much appreciated

Thanks in Advance

**Comment by RobHolme** [comment]
In this example only one of the OBX segments contain an OBX-18 field, so this is why only one value is returned.

Nothing wrong with your query - looks to be a defect with the code. At the very least the results should be consistent, I can see how based on your first example you would expect the empty OBX-18 fields to be included in these results. Makes sense to only include values where the filter match occurred as per your first email.
________________________________

**Comment by RobHolme** [comment]
Thinking about this further, it will be difficult to implement. The filter condition may be unrelated to the item returned. e.g. if you are filtering on a PID field but returning an OBX field. My intent for the -Filter parameter was to filter at the message level when scanning a large number of messages, not really something I intended to filter elements within a single message.  

e.g Select-HL7Item -path c:\test\lab-results\*.* -ItemPosition OBX-3 -Filter PID-3.1=X999999

This would filter through 100's of messages within the c:\test\lab-results\ folder, but only return OBX-3 for messages with the patient ID of X999999. All other messages would be excluded from the results. My intent behind these commands were to support examining a large numbers of messages - if working with single messages a dedicated HL7 file editor may serve a better fit.

**Comment by srikcgaa2** [comment]
Thanks for the quick response and clarifications.  I do have multiple HL7 files but I am interested only in OBX-3 which has OBX-2=NM.    How do I filter segments with just this match?  Even if I replace single file with *.hl7, I am getting other OBX that does not have OBX-2=NM

In addition, if I change the ItemPosition as follows, I am ending up with different number of matches for different fields

`Select-HL7Item -path <file> -ItemPosition OBX-3.2,6.2 -Filter OBX-2=NM`

For the above arguments, I get 13 matches for OBX-3.2 and 3 matches for OBX-6.2.  In my case, 6.2 is the numeric value and 3.2 is the name of the measurement when OBX-2 = NM.

**Comment by RobHolme** [comment]
The filter doesn't filter on specific fields or segments, it is just a filter to decide to include the entire message or discard it from the query. Once the filter identifies that a message matches the filter value, then it selects the fields requested for the **entire message** i.e. the filter only decides on what messages are queried, it does not alter the query that is made against those messages. The query above is essentially saying "for all messages which contain an OBX-2 value equal to 'NM', display all OBX-3.2 and OBX-6.2 values for every OBX segment in the message".

If you needed to only display specific OBX segments from the results returned, then you can pipe the results and apply further filtering in Powershell. The example below pipes all OBX segments returned and looks for a regex match where the segment contains an OBX-3 value of NM. The first command will return the entire maching OBX segment, the second example refines this to only display the OBX-3 value.

![image](https://user-images.githubusercontent.com/23287323/187851165-2605a300-46c7-438b-9ba7-2a38977b81bb.png)


```(Select-HL7Item -path '202208300638_001738_ORU.R01.txt' -ItemPosition OBX -Filter OBX-2=NM).OBX | foreach {if ($_ -match "OBX\|[0-9]+\|NM\|") {$_.split("|")[3]}}```
 

The command in your reply above will return different number of OBX-6.2 values to OBX-3 because the message contains more OBX-3 values - several of the OBX segments don't include a value for OBX-6.2. I can see in your example there may be value in including the empty values in the array of values returned - I'll look into changing this behaviour when I find time.

**Comment by srikcgaa2** [comment]
Awesome and thank you once again for the quick response along with suggesion on the solution for the problem as well.  In this case, inclusion of the -filter OBX-2=NM  gave me same number of matches as it does without the filter as well which is where I was thinking if I was making a mistake.  

I have also updated my script to loop through all OBX and include processing only when OBX-2 matches NM and so I have a workaround for this problem.  So I am good for now but from the response it looks like there could be future enhancements possible as well.

**Comment by RobHolme** [comment]
I've publish v1.7.11. This version will return empty values in the array of values returned if the message segment does not include the field/component/subcomponent being queried. So for repeating segments, the number of values returned should align with the number of segments present in the message. e.g.

![image](https://user-images.githubusercontent.com/23287323/188256724-d022eed6-31d3-4fb9-89a7-424d41c32da2.png)

**Comment by srikcgaa2** [comment]
Thanks.  Will install the update once available.

**Comment by srikcgaa2** [comment]
I see it is already published.  Will use this version going forward
