### ISSUE TITLE
Non PowerShell Users Question

### ISSUE THREAD

**Issue by Noggin79s** [RobHolme/HL7-Powershell-Module#8]
We are looking for a way to roll out a tool to our users for them to test their Network connections to our Integration Engine from their servers. 

While most Windows systems have PowerShell included, do you know of a way that we could make tools into an app outside of PowerShell that could easily be deployable to customers?

**Comment by RobHolme** [comment]
Personally, I'd stick with tools already available rather than writing your own. 

Windows based systems should have PowerShell available, so I'd go with `Test-NetConnection` to test connectivity to a TCP port on a remote host. For Linux based systems, install netcat (`nc`) and use it to test connectivity to a TCP port on a remote host.  

If you are intent on writing your own tool, this sounds like more of a question for Stack Overflow (or Google). Plenty of code examples out there on how to write a TCP client in your preferred development environment. If you are sticking to .Net environments take a look at System.Net.Sockets.TcpClient documentation. To confirm you have connectivity you would only need to confirm the TCP connection was successful, then close the connection. No need to write any data to the socket or wait for a response - just establishing the connection should be sufficient to confirm network connectivity. Any exceptions thrown would indicate a failed connection. 

As this issue seems to be unrelated to an issue with this PowerShell module I'll close it off.

**Comment by RobHolme** [comment]
Or if the intent is to test a message being received, rather than confirming TCP connectivity, then yes it's possible for you to re-write the Send-HL7Message function as a non-PowerShell app. But again I would recommend using something that already exists rather than spending your effort on converting the source to remove the PowerShell dependencies.

Take a look at SmartHL7 tools - this includes a suite of Windows HL7 tools:  
https://foldda.com/wp-content/uploads/2021/08/SmartHL7.Tools_.Bundle.2021.zip  

The HL7 Message Sender app from the bundle looks like it would suit your needs (https://foldda.com/2021/08/01/hl7-message-sender/)
